name: Cypress Smoke Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to test'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod

env:
  CYPRESS_BASE_URL: ${{ github.event.inputs.environment == 'prod' && 'https://admin.notifynl.nl/' || 'https://admin.test.notifynl.nl/' }}

jobs:
  cypress-run:
    name: Smoke test for (${{ github.event.inputs.environment }}) environment
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          spec: cypress/e2e/smoke.cy.js
        env:
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}
